### ISSUE TITLE
Recommend adding the repo url to your python package

### ISSUE THREAD

**Issue by jacklinke** [snake-soft/django-htmx-viewsets#7]
You've got some pretty cool packages on PyPI, but you don't provide the url to your GitHub repo in the setup.py, so it is incredibly difficult to find the source code and contribute.

Recommend you [add the repo url to your package](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#url) so that people can navigate here from PyPI. It will increase the number of folks who use and can contribute fixes back to your codebase.

**Comment by snake-soft** [comment]
Fixed, thank you for tracking.
